### ISSUE TITLE
#Define loc imagen ha de ser con locno

### ISSUE THREAD

**Issue by cibersheep** [Baltasarq/txtpaws#1]
¡Buenas! Mira a qué horas llego yo a txtpaws ^_^

Estoy usando ngPAWS y veo que para adaptar algunas aventuras sería de gran utilidad porder definir al principio de esta manera:
```
 #define loc lFrontera 3
 #define pic loc03.png lFrontera
```
Ahora, este código se sustituye por:
```
 #define loc lFrontera 3
 #define pic loc03.png o
```
Acabo de ver en la wiki que una forma de hacerlo por ahora sería:
```
/LTX
/3 = lFrontera(loc03.png)
```

PD: Viene de [aquí](https://github.com/Utodev/ngPAWS/issues/17)

**Comment by Baltasarq** [comment]
txtPAWS has no way to know whether something substituted contents has or no labels. The look for labels in substituted content could easily become an infinite loop.

Note that **txtPAWS** was originally conceived as a simple preprocessor *a la* cpp, but grew to manage multimedia assets and many more characteristics (probably due to my own enthusiastic attitude, my fault).
These puts a lot of weight off the shoulders of *Superglus/ngPAWS* and the like programmers, but looking to the past it was an error: **txtPAWS** should have existed meanwhile labels and multimedia assets management were not added to *Superglus/ngPAWS*. In general, preprocessors are auxiliary tools, not vital parts.

So, yes to to bugfixes, no to new features, and certainly no to look for labels in substituted content, which could potentially break execution. As you noted, there are other approaches that serve the objective you were pursuing.

**Comment by cibersheep** [comment]
Thanks for answering. I see your point here.
Best regards
